import DataService from './data.service';
import ErrorService from './error.service';

import { ERole } from './../classes/Role';

export const ERights = {
  APP_CAN_USE_GPS: 'APP_CAN_USE_GPS',
  APP_CAN_USE_LOGTRACK: 'APP_CAN_USE_LOGTRACK',
  APP_CAN_USE_CONTRACT_MANAGEMENT: 'APP_CAN_USE_CONTRACT_MANAGEMENT',
  APP_CAN_USE_EMPLOYEE_MANAGEMENT: 'APP_CAN_USE_EMPLOYEE_MANAGEMENT',
  APP_CAN_USE_EQUIPMENT_MANAGEMENT: 'APP_CAN_USE_EQUIPMENT_MANAGEMENT',
  APP_CAN_USE_WAREHOUSE_MANAGEMENT: 'APP_CAN_USE_WAREHOUSE_MANAGEMENT',
  APP_CAN_USE_ANALYTICS: 'APP_CAN_USE_ANALYTICS',
  APP_CAN_USE_JOBOFFERS_MANAGEMENT: 'APP_CAN_USE_JOBOFFERS_MANAGEMENT',

  RIGHT_BRAND_CREATE: 'RIGHT_BRAND_CREATE',
  RIGHT_BRAND_GET: 'RIGHT_BRAND_GET',
  RIGHT_BRAND_LIST: 'RIGHT_BRAND_LIST',
  RIGHT_BRAND_UPDATE: 'RIGHT_BRAND_UPDATE',
  RIGHT_BRAND_DELETE: 'RIGHT_BRAND_DELETE',

  RIGHT_COMPANY_CREATE: 'RIGHT_COMPANY_CREATE',
  RIGHT_COMPANY_GET: 'RIGHT_COMPANY_GET',
  RIGHT_COMPANY_LIST: 'RIGHT_COMPANY_LIST',
  RIGHT_COMPANY_UPDATE: 'RIGHT_COMPANY_UPDATE',
  RIGHT_COMPANY_DELETE: 'RIGHT_COMPANY_DELETE',

  RIGHT_JOBOFFERS_CREATE: 'RIGHT_JOBOFFERS_CREATE',
  RIGHT_JOBOFFERS_GET: 'RIGHT_JOBOFFERS_GET',
  RIGHT_JOBOFFERS_LIST: 'RIGHT_JOBOFFERS_LIST',
  RIGHT_JOBOFFERS_UPDATE: 'RIGHT_JOBOFFERS_UPDATE',
  RIGHT_JOBOFFERS_DELETE: 'RIGHT_JOBOFFERS_DELETE',

  RIGHT_CONTRACT_CREATE: 'RIGHT_CONTRACT_CREATE',
  RIGHT_CONTRACT_GET: 'RIGHT_CONTRACT_GET',
  RIGHT_CONTRACT_LIST: 'RIGHT_CONTRACT_LIST',
  RIGHT_CONTRACT_UPDATE: 'RIGHT_CONTRACT_UPDATE',
  RIGHT_CONTRACT_DELETE: 'RIGHT_CONTRACT_DELETE',

  RIGHT_EMPLOYEE_CREATE: 'RIGHT_EMPLOYEE_CREATE',
  RIGHT_EMPLOYEE_GET: 'RIGHT_EMPLOYEE_GET',
  RIGHT_EMPLOYEE_LIST: 'RIGHT_EMPLOYEE_LIST',
  RIGHT_EMPLOYEE_UPDATE: 'RIGHT_EMPLOYEE_UPDATE',
  RIGHT_EMPLOYEE_DELETE: 'RIGHT_EMPLOYEE_DELETE',

  RIGHT_ACCOUNT_ACTIVITY_CREATE: 'RIGHT_ACCOUNT_ACTIVITY_CREATE',
  RIGHT_ACCOUNT_ACTIVITY_GET: 'RIGHT_ACCOUNT_ACTIVITY_GET',
  RIGHT_ACCOUNT_ACTIVITY_LIST: 'RIGHT_ACCOUNT_ACTIVITY_LIST',
  RIGHT_ACCOUNT_ACTIVITY_UPDATE: 'RIGHT_ACCOUNT_ACTIVITY_UPDATE',
  RIGHT_ACCOUNT_ACTIVITY_DELETE: 'RIGHT_ACCOUNT_ACTIVITY_DELETE',
  
  RIGHT_EQUIPMENT_MODEL_CREATE: 'RIGHT_EQUIPMENT_MODEL_CREATE',
  RIGHT_EQUIPMENT_MODEL_GET: 'RIGHT_EQUIPMENT_MODEL_GET',
  RIGHT_EQUIPMENT_MODEL_LIST: 'RIGHT_EQUIPMENT_MODEL_LIST',
  RIGHT_EQUIPMENT_MODEL_UPDATE: 'RIGHT_EQUIPMENT_MODEL_UPDATE',
  RIGHT_EQUIPMENT_MODEL_DELETE: 'RIGHT_EQUIPMENT_MODEL_DELETE',
  
  RIGHT_EQUIPMENT_CREATE: 'RIGHT_EQUIPMENT_CREATE',
  RIGHT_EQUIPMENT_GET: 'RIGHT_EQUIPMENT_GET',
  RIGHT_EQUIPMENT_LIST: 'RIGHT_EQUIPMENT_LIST',
  RIGHT_EQUIPMENT_UPDATE: 'RIGHT_EQUIPMENT_UPDATE',
  RIGHT_EQUIPMENT_DELETE: 'RIGHT_EQUIPMENT_DELETE',

  RIGHT_LOGTRACK_CREATE: 'RIGHT_LOGTRACK_CREATE',
  RIGHT_LOGTRACK_GET: 'RIGHT_LOGTRACK_GET',
  RIGHT_LOGTRACK_LIST: 'RIGHT_LOGTRACK_LIST',
  RIGHT_LOGTRACK_UPDATE: 'RIGHT_LOGTRACK_UPDATE',
  RIGHT_LOGTRACK_DELETE: 'RIGHT_LOGTRACK_DELETE',

  RIGHT_ROLE_CREATE: 'RIGHT_ROLE_CREATE',
  RIGHT_ROLE_GET: 'RIGHT_ROLE_GET',
  RIGHT_ROLE_LIST: 'RIGHT_ROLE_LIST',
  RIGHT_ROLE_UPDATE: 'RIGHT_ROLE_UPDATE',
  RIGHT_ROLE_DELETE: 'RIGHT_ROLE_DELETE',

  RIGHT_SUPPORT_CREATE: 'RIGHT_SUPPORT_CREATE',
  RIGHT_SUPPORT_GET: 'RIGHT_SUPPORT_GET',
  RIGHT_SUPPORT_LIST: 'RIGHT_SUPPORT_LIST',
  RIGHT_SUPPORT_UPDATE: 'RIGHT_SUPPORT_UPDATE',
  RIGHT_SUPPORT_DELETE: 'RIGHT_SUPPORT_DELETE',

  RIGHT_WAREHOUSE_CREATE: 'RIGHT_WAREHOUSE_CREATE',
  RIGHT_WAREHOUSE_GET: 'RIGHT_WAREHOUSE_GET',
  RIGHT_WAREHOUSE_LIST: 'RIGHT_WAREHOUSE_LIST',
  RIGHT_WAREHOUSE_UPDATE: 'RIGHT_WAREHOUSE_UPDATE',
  RIGHT_WAREHOUSE_DELETE: 'RIGHT_WAREHOUSE_DELETE',

  RIGHT_WEATHER_CREATE: 'RIGHT_WEATHER_CREATE',
  RIGHT_WEATHER_GET: 'RIGHT_WEATHER_GET',
  RIGHT_WEATHER_LIST: 'RIGHT_WEATHER_LIST',
  RIGHT_WEATHER_UPDATE: 'RIGHT_WEATHER_UPDATE',
  RIGHT_WEATHER_DELETE: 'RIGHT_WEATHER_DELETE'
};

const RightService = {
  hasAppRight: right => {
    if(!DataService.computed.activeRole) {
      return false;
    }

    if(right === ERights.APP_CAN_USE_GPS) {
      return DataService.computed.activeRole.role === ERole.DRIVER;
    }

    if(right === ERights.APP_CAN_USE_LOGTRACK) {
      return DataService.computed.activeRole.role === ERole.DRIVER ||
        DataService.computed.activeRole.role === ERole.MECHANIC;
    }
    if(right === ERights.APP_CAN_USE_CONTRACT_MANAGEMENT ||
        right === ERights.APP_CAN_USE_EMPLOYEE_MANAGEMENT ||
        right === ERights.APP_CAN_USE_EQUIPMENT_MANAGEMENT ||
        right === ERights.APP_CAN_USE_WAREHOUSE_MANAGEMENT ||
        right === ERights.APP_CAN_USE_ANALYTICS) {

      return DataService.computed.activeRole.role === ERole.MANAGER;
    }
    if(right === ERights.APP_CAN_USE_JOBOFFERS_MANAGEMENT) {
      return DataService.computed.activeRole.role === ERole.MANAGER ||
        DataService.computed.activeRole.role === ERole.RECRUITER;
    }

    ErrorService.error('Right ' + right + ' is unknown');
    return false;
  }
};

export default RightService;
