import { faWater, faSeedling, faTrees, faGem, faWheat, faSteak, faEgg, faFish, 
    faCarrot, faAppleAlt, faTint, faCookie, faCandyCane, faCheeseSwiss, faPizzaSlice, 
    faIceCream, faWineBottle, faTurkey, faFishCooked, faSoup, faSalad, faBeer, 
    faPuzzlePiece, faTv, faCarSide, faTshirt, faCogs, faGlassCheers, faCouch, faBlender, 
    faBooks, faStickyNote, faMoneyBill, faToothbrush, faMailBulk, faContainerStorage, 
    faPalletAlt, faBaseball, faGuitar, faStretcher, faShower, faPlug, faTrafficCone, 
    faTractor, faBroadcastTower, faIndustryAlt, faBolt, faHammer, faPig, faElephant, 
    faHorse, faDog, faBiohazard, faAtom, faRadiation, faSkullCrossbones, faVial, faGasPump, 
    faBurn, faTrash, faRecycle, faPills, faLungs, faSyringe, faGlasses, faTooth, faBaby } from '@fortawesome/pro-light-svg-icons';

import ELoadMeasure from './ELoadMeasure';
import ELoadCool from './ELoadCool';

const ELoadType = Object.freeze({
    RAW_MATERIALS: {
        code: 'RAW_MATERIALS', 
        name: 'Raw Materials', 
        icon: 'Rocks',
        iconSource: 'custom',
        subTypes: {
            WATER: {code: 'WATER', name: 'Water', icon: faWater, iconSource: 'fa', 
                cooled: [ELoadCool.NONE], 
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            PLANTS: {code: 'PLANTS', name: 'Plants', icon: faSeedling, iconSource: 'fa', 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            WOOD: {code: 'WOOD', name: 'Wood', icon: faTrees, iconSource: 'fa',
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            PRECIOUS: {code: 'PRECIOUS', name: 'Precious Materials', icon: faGem, iconSource: 'fa',
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            ROCKS: {code: 'ROCKS', name: 'Rocks', icon: 'Rocks', iconSource: 'custom',
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            CONSTRUCTION_MATERIAL: {code: 'CONTRUCTION_MATERIAL', name: 'Construction Materials', icon: 'ConstructionMaterial', iconSource: 'custom', 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
    }},
    RAW_FOOD: {
        code: 'RAW_FOOD',
        name: 'Raw Food',
        icon: faCarrot,
        iconSource: 'fa',
        subTypes: {
            CEREALS: {code: 'CEREALS', name: 'Cereals', icon: faWheat, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            MEAT: {code: 'MEAT', name: 'Meat', icon: faSteak, 
                cooled: [ELoadCool.FROZEN, ELoadCool.REFRIGERATED],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.NUMBER, ELoadMeasure.WEIGHT]},
            EGGS: {code: 'EGGS', name: 'Eggs', icon: faEgg, 
                cooled: [ELoadCool.FROZEN, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            FISH: {code: 'FISH', name: 'Fish', icon: faFish, 
                cooled: [ELoadCool.FROZEN, ELoadCool.REFRIGERATED],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            VEGETABLES: {code: 'VEGETABLES', name: 'Vegetables', icon: faCarrot, 
                cooled: [ELoadCool.FROZEN, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            FRUITS: {code: 'FRUITS', name: 'Fruits', icon:faAppleAlt, 
                cooled: [ELoadCool.FROZEN, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            MILK: {code: 'MILK', name: 'Milk', icon: faTint, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
    }},
    TRANSFORMED_FOOD: {
        code: 'TRANSFORMED_FOOD',
        name: 'Transformed Food',
        icon: faPizzaSlice,
        iconSource: 'fa',
        subTypes: {
            BISCUITS: {code: 'BISCUITS', name: 'Biscuits', icon: faCookie, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            CANDIES: {code: 'CANDIES', name: 'Candies', icon: faCandyCane, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            CHEESE: {code: 'CHEESE', name: 'Cheese', icon: faCheeseSwiss, 
                cooled: [ELoadCool.REFRIGERATED],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            FOOD_PRODUCT: {code: 'FOOD_PRODUCT', name: 'Food Product', icon: faPizzaSlice, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            ICE_CREAM: {code: 'ICE_CREAM', name: 'Ice Cream', icon: faIceCream, 
                cooled: [ELoadCool.FROZEN],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            WINE: {code: 'WINE', name: 'Wine', icon: faWineBottle, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            COOKED_MEAT: {code: 'COOKED_MEAT', name: 'Cooked Meat', icon: faTurkey, 
                cooled: [ELoadCool.FROZEN, ELoadCool.REFRIGERATED],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            COOKED_FISH: {code: 'COOKED_FISH', name: 'Cooked Fish', icon: faFishCooked, 
                cooled: [ELoadCool.FROZEN, ELoadCool.REFRIGERATED],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            RAW_MEAT: {code: 'RAW_MEAT', name: 'Raw Meat', icon: faSteak, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            SOUP: {code: 'SOUP', name: 'Soup', icon: faSoup, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            SALAD: {code: 'SALAD', name: 'Salad', icon: faSalad, 
                cooled: [ELoadCool.FROZEN, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            DRINKS: {code: 'DRINKS', name: 'Drinks', icon: faBeer, 
                cooled: [ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            TOYS: {code: 'TOYS', name: 'Toys', icon: faPuzzlePiece, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
    }},
    MANUFACTURED_PRODUCTS: {
        code: 'MANUFACTURED_PRODUCTS',
        name: 'Manufactured Products',
        icon: faCouch,
        iconSource: 'fa',
        subTypes: {
            ELECTRONICS: {code: 'ELECTRONICS', name: 'Electronics', icon: faTv, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET]},
            AUTOMOTIVE: {code: 'AUTOMOTIVE', name: 'Automotive', icon: faCarSide, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.WEIGHT]},
            GARNMENTS: {code: 'GARNMENTS', name: 'Garnments', icon: faTshirt, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            PARTS: {code: 'PARTS', name: 'Parts', icon: faCogs, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            DISHES: {code: 'DISHES', name: 'Dishes', icon: faGlassCheers, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            FURNITURE: {code: 'FURNITURE', name: 'Furniture', icon: faCouch, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            APPLIANCE: {code: 'APPLIANCE', name: 'Applicance', icon: faBlender, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            BOOKS: {code: 'BOOKS', name: 'Books', icon: faBooks, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET]},
            OFFICE_SUPPLIES: {code: 'OFFICE_SUPPLIES', name: 'Office Supplies', icon: faStickyNote, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            MONEY: {code: 'MONEY', name: 'Money', icon: faMoneyBill, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME]},
            HYGIENE: {code: 'HYGIENE', name: 'Hygiene', icon: faToothbrush, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            BABY_FURNITURE: {code: 'BABY_FURNITURE', name: 'Baby Furniture', icon: faBaby,
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],
                measures: [ELoadMeasure.CONTAINER, ELoadCool.NUMBER, ELoadCool.PALLET, ELoadCool.WEIGHT]},
            MAIL: {code: 'MAIL', name: 'Mail', icon: faMailBulk,
                cooled: [ELoadCool.NONE, ELoadCool.STABLE, ELoadCool.REFRIGERATED],
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]}
    }},
    TRANSPORT: {
        code: 'TRANSPORT',
        name: 'Transport',
        icon: faContainerStorage,
        iconSource: 'fa',
        subTypes: {
            CONTAINER: {code: 'CONTAINER', name: 'Container', icon: faContainerStorage,
                cooled: [ELoadCool.NONE],
                measures: [ELoadMeasure.CONTAINER]},
            PALLET: {code: 'PALLET', name: 'Pallet', icon: faPalletAlt,
                cooled: [ELoadCool.NONE],
                measures: [ELoadMeasure.PALLET, ELoadMeasure.NUMBER]}
        }
    },
    EQUIPMENT: {
        code: 'EQUIPMENT',
        name: 'Equipment',
        icon: faPlug,
        iconSource: 'fa',
        subTypes: {
            SPORTS_EQUIPMENT: {code: 'SPORTS_EQUIPMENT', name: 'Sports Equipment', icon: faBaseball, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            MUSIC_EQUIPMENT: {code: 'MUSIC_EQUIPMENT', name: 'Music Equipment', icon: faGuitar, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            MEDICAL_EQUIPMENT: {code: 'MEDICAL_EQUIPMENT', name: 'Medical Equipment', icon: faStretcher, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            PLUMBING_EQUIPMENT: {code: 'PLUMBING_EQUIPMENT', name: 'Plumbing Equipment', icon: faShower, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            ELECTRIC_EQUIPMENT: {code: 'ELECTRIC_EQUIPMENT', name: 'Electric Equipment', icon: faPlug, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            CONSTRUCTION_EQUIPMENT: {code: 'CONSTRUCTION_EQUIPMENT', name: 'Construction Equipment', icon: faTrafficCone, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            AGRICULTURE_EQUIPMENT: {code: 'AGRICULTURE_EQUIPMENT', name: 'Agriculture Equipment', icon: faTractor,
                cooled: [ELoadCool.NONE],
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            RADIO_EQUIPMENT: {code: 'RADIO_EQUIPMENT', name: 'Radio Equipment', icon: faBroadcastTower, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            INDUSTRIAL_EQUIPMENT: {code: 'INDUSTRIAL_EQUIPMENT', name: 'Industrial Equipment', icon: faIndustryAlt, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            ENERGY_EQUIPMENT: {code: 'ENERGY_EQUIPMENT', name: 'Energy Equipment', icon: faBolt, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            CRAFTS: {code: 'CRAFTS', name: 'Crafts', icon: faHammer,
                cooled: [ELoadCool.STABLE, ELoadCool.NONE],
                measures: [ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT, ELoadMeasure.CONTAINER]}
    }},
    LIVE_ANIMALS: {
        code: 'LIVE_ANIMALS',
        name: 'Live Animals',
        icon: faElephant,
        iconSource: 'fa',
        subTypes: {
            BARN_LIVE_ANIMALS: {code: 'BARN_LIVE_ANIMALS', name: 'Barn Animals', icon: faPig, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.NUMBER, ELoadMeasure.WEIGHT]},
            EXOTICS_ANIMALS: {code: 'EXOTIC_ANIMALS', name: 'Exotic Animals', icon: faElephant, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.NUMBER, ELoadMeasure.WEIGHT]},
            COMPETITION_ANIMALS: {code: 'COMPETITION_ANIMALS', name: 'Competition Animals', icon: faHorse, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.NUMBER, ELoadMeasure.WEIGHT]},
            OTHER_ANIMALS: {code: 'OTHER_ANIMALS', name: 'Other Animals', icon: faDog,
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],
                measures: [ELoadMeasure.NUMBER]}
    }},
    HAZARD: {
        code: 'HAZARD',
        name: 'Hazard',
        icon: faSkullCrossbones,
        iconSource: 'fa',
        subTypes: {
            BIOHAZARD: {code: 'BIOHAZARD', name: 'Biohazard', icon: faBiohazard, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            HAZARD_MATERIAL: {code: 'HAZARD_MATERIAL', name: 'Hazard Materials', icon: faAtom, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            RADIATION: {code: 'RADIATION', name: 'Radiation', icon: faRadiation, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            TOXIC: {code: 'TOXIC', name: 'Toxic', icon: faSkullCrossbones, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            UNSTABLE: {code: 'UNSTABLE', name: 'Unstable Materials', icon: faVial, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            GAS: {code: 'GAS', name: 'Gas', icon: faGasPump, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            FLAMMABLE: {code: 'FLAMMABLE', name: 'Flammable', icon: faBurn, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
    }},
    TRASH: {
        code: 'TRASH',
        name: 'Trash',
        icon: faTrash,
        iconSource: 'fa',
        subTypes: {
            TRASH: {code: 'TRASH', name: 'Trash', icon: faTrash, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            RECYCLE: {code: 'RECYCLE', name: 'Recycle', icon: faRecycle, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
    }},
    MEDICAL: {
        code: 'MEDICAL',
        name: 'Medical',
        icon: faSyringe,
        iconSource: 'fa',
        subTypes: {
            PHARMACEUTICALS: {code: 'PHARMACEUTICALS', name: 'Pharmaceuticals', icon: faPills, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            ORGANS: {code: 'ORGANS', name: 'Organs', icon: faLungs, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.NUMBER]},
            MEDICAL_FURNITURE: {code: 'MEDICAL_FURNITURE', name: 'Medical Furniture', icon: faSyringe, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            VISION: {code: 'VISIION', name: 'Vision', icon: faGlasses,
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],
                measures: [ELoadMeasure.PALLET, ELoadCool.CONTAINER]},
            TOOTH: {code: 'TOOTH', name: 'Tooth', icon: faTooth,
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],
                ELoadMeasure: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET]}
    }},
});

export default ELoadType;
