import React from 'react';

import { faWater, faSeedling, faTrees, faGem, faWheat, faSteak, faEgg, faFish, 
    faCarrot, faAppleAlt, faTint, faCookie, faCandyCane, faCheeseSwiss, faPizzaSlice, 
    faIceCream, faWineBottle, faTurkey, faFishCooked, faSoup, faSalad, faBeer, 
    faPuzzlePiece, faTv, faCarSide, faTshirt, faCogs, faGlassCheers, faCouch, faBlender, 
    faBooks, faStickyNote, faMoneyBill, faToothbrush, faMailBulk, faContainerStorage, 
    faPalletAlt, faBaseball, faGuitar, faStretcher, faShower, faPlug, faTrafficCone, 
    faTractor, faBroadcastTower, faIndustryAlt, faBolt, faHammer, faPig, faElephant, 
    faHorse, faDog, faBiohazard, faAtom, faRadiation, faSkullCrossbones, faVial, faGasPump, 
    faBurn, faTrash, faRecycle, faPills, faLungs, faSyringe, faGlasses, faTooth, faBaby } from '@fortawesome/pro-solid-svg-icons';

import Icon from './../../components/Utils/Icon/Icon';

import ELoadMeasure from './ELoadMeasure';
import ELoadCool from './ELoadCool';

const ELoadType = Object.freeze({
    RAW_MATERIALS: {
        code: 'RAW_MATERIALS', 
        name: 'Raw Materials', 
        subTypes: {
            WATER: {code: 'WATER', name: 'Water', icon: <Icon source="fa" icon={faWater} />, 
                cooled: [ELoadCool.NONE], 
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            PLANTS: {code: 'PLANTS', name: 'PLANTS', icon: <Icon source="fa" icon={faSeedling} />, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            WOOD: {code: 'WOOD', name: 'Wood', icon: <Icon source="fa" icon={faTrees} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            PRECIOUS: {code: 'PRECIOUS', name: 'Precious Materials', icon: <Icon source="fa" icon={faGem} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            ROCKS: {code: 'ROCKS', name: 'Rocks', icon: <Icon source="custom" icon="Rocks" />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            CONSTRUCTION_MATERIAL: {code: 'CONTRUCTION_MATERIAL', name: 'Construction Materials', icon: <Icon source="custom" icon="ConstructionMaterial" />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
    }},
    RAW_FOOD: {
        code: 'RAW_FOOD',
        name: 'Raw Food',
        subTypes: {
            CEREALS: {code: 'CEREALS', name: 'Cereals', icon: <Icon source="fa" icon={faWheat} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            MEAT: {code: 'MEAT', name: 'Meat', icon: <Icon source="fa" icon={faSteak} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.REFRIGERATED],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.NUMBER, ELoadMeasure.WEIGHT]},
            EGGS: {code: 'EGGS', name: 'Eggs', icon: <Icon source="fa" icon={faEgg} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            FISH: {code: 'FISH', name: 'Fish', icon: <Icon source="fa" icon={faFish} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.REFRIGERATED],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            VEGETABLES: {code: 'VEGETABLES', name: 'Vegetables', icon: <Icon source="fa" icon={faCarrot} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            FRUITS: {code: 'FRUITS', name: 'Fruits', icon: <Icon source="fa" icon={faAppleAlt} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            MILK: {code: 'MILK', name: 'Milk', icon: <Icon source="fa" icon={faTint} />, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
    }},
    TRANSFORMED_FOOD: {
        code: 'TRANSFORMED_FOOD',
        name: 'Transformed Food',
        subTypes: {
            BISCUITS: {code: 'BISCUITS', name: 'Biscuits', icon: <Icon source="fa" icon={faCookie} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            CANDIES: {code: 'CANDIES', name: 'Candies', icon: <Icon source="fa" icon={faCandyCane} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            CHEESE: {code: 'CHEESE', name: 'Cheese', icon: <Icon source="fa" icon={faCheeseSwiss} />, 
                cooled: [ELoadCool.REFRIGERATED],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            FOOD_PRODUCT: {code: 'FOOD_PRODUCT', name: 'Food Product', icon: <Icon source="fa" icon={faPizzaSlice} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            ICE_CREAM: {code: 'ICE_CREAM', name: 'Ice Cream', icon: <Icon source="fa" icon={faIceCream} />, 
                cooled: [ELoadCool.FROZEN],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            WINE: {code: 'WINE', name: 'Wine', icon: <Icon source="fa" icon={faWineBottle} />, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            COOKED_MEAT: {code: 'COOKED_MEAT', name: 'Cooked Meat', icon: <Icon source="fa" icon={faTurkey} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.REFRIGERATED],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            COOKED_FISH: {code: 'COOKED_FISH', name: 'Cooked Fish', icon: <Icon source="fa" icon={faFishCooked} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.REFRIGERATED],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            RAW_MEAT: {code: 'RAW_MEAT', name: 'Raw Meat', icon: <Icon source="fa" icon={faSteak} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            SOUP: {code: 'SOUP', name: 'Soup', icon: <Icon source="fa" icon={faSoup} />, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            SALAD: {code: 'SALAD', name: 'Salad', icon: <Icon source="fa" icon={faSalad} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            DRINKS: {code: 'DRINKS', name: 'Drinks', icon: <Icon source="fa" icon={faBeer} />, 
                cooled: [ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            TOYS: {code: 'TOYS', name: 'Toys', icon: <Icon source="fa" icon={faPuzzlePiece} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
    }},
    MANUFACTURED_PRODUCTS: {
        code: 'MANUFACTURED_PRODUCTS',
        name: 'Manufactured Products',
        subTypes: {
            ELECTRONICS: {code: 'ELECTRONICS', name: 'Electronics', icon: <Icon source="fa" icon={faTv} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET]},
            AUTOMOTIVE: {code: 'AUTOMOTIVE', name: 'Automotive', icon: <Icon source="fa" icon={faCarSide} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.WEIGHT]},
            GARNMENTS: {code: 'GARNMENTS', name: 'Garnments', icon: <Icon source="fa" icon={faTshirt} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            PARTS: {code: 'PARTS', name: 'Parts', icon: <Icon source="fa" icon={faCogs} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            DISHES: {code: 'DISHES', name: 'Dishes', icon: <Icon source="fa" icon={faGlassCheers} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            FURNITURE: {code: 'FURNITURE', name: 'Furniture', icon: <Icon source="fa" icon={faCouch} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            APPLIANCE: {code: 'APPLIANCE', name: 'Applicance', icon: <Icon source="fa" icon={faBlender} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            BOOKS: {code: 'BOOKS', name: 'Books', icon: <Icon source="fa" icon={faBooks} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET]},
            OFFICE_SUPPLIES: {code: 'OFFICE_SUPPLIES', name: 'Office Supplies', icon: <Icon source="fa" icon={faStickyNote} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            MONEY: {code: 'MONEY', name: 'Money', icon: <Icon source="fa" icon={faMoneyBill} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME]},
            HYGIENE: {code: 'HYGIENE', name: 'Hygiene', icon: <Icon source="fa" icon={faToothbrush} />, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            BABY_FURNITURE: {code: 'BABY_FURNITURE', name: 'Baby Furniture', icon: <Icon source="fa" icon={faBaby} />,
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],
                measures: [ELoadMeasure.CONTAINER, ELoadCool.NUMBER, ELoadCool.PALLET, ELoadCool.WEIGHT]},
            MAIL: {code: 'MAIL', name: 'Mail', icon: <Icon source="fa" icon={faMailBulk} />,
                cooled: [ELoadCool.NONE, ELoadCool.STABLE, ELoadCool.REFRIGERATED],
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]}
    }},
    TRANSPORT: {
        code: 'TRANSPORT',
        name: 'Transport',
        subTypes: {
            CONTAINER: {code: 'CONTAINER', name: 'Container', icon: <Icon source="fa" icon={faContainerStorage} />,
                cooled: [ELoadCool.NONE],
                measures: [ELoadMeasure.CONTAINER]},
            PALLET: {code: 'PALLET', name: 'Pallet', icon: <Icon source="fa" icon={faPalletAlt} />,
                cooled: [ELoadCool.NONE],
                measures: [ELoadMeasure.PALLET, ELoadMeasure.NUMBER]}
        }
    },
    EQUIPMENT: {
        code: 'EQUIPMENT',
        name: 'Equipment',
        subTypes: {
            SPORTS_EQUIPMENT: {code: 'SPORTS_EQUIPMENT', name: 'Sports Equipment', icon: <Icon source="fa" icon={faBaseball} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            MUSIC_EQUIPMENT: {code: 'MUSIC_EQUIPMENT', name: 'Music Equipment', icon: <Icon source="fa" icon={faGuitar} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            MEDICAL_EQUIPMENT: {code: 'MEDICAL_EQUIPMENT', name: 'Medical Equipment', icon: <Icon source="fa" icon={faStretcher} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            PLUMBING_EQUIPMENT: {code: 'PLUMBING_EQUIPMENT', name: 'Plumbing Equipment', icon: <Icon source="fa" icon={faShower} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            ELECTRIC_EQUIPMENT: {code: 'ELECTRIC_EQUIPMENT', name: 'Electric Equipment', icon: <Icon source="fa" icon={faPlug} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            CONSTRUCTION_EQUIPMENT: {code: 'CONSTRUCTION_EQUIPMENT', name: 'Construction Equipment', icon: <Icon source="fa" icon={faTrafficCone} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            AGRICULTURE_EQUIPMENT: {code: 'AGRICULTURE_EQUIPMENT', name: 'Agriculture Equipment', icon: <Icon source="fa" icon={faTractor} />,
                cooled: [ELoadCool.NONE],
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            RADIO_EQUIPMENT: {code: 'RADIO_EQUIPMENT', name: 'Radio Equipment', icon: <Icon source="fa" icon={faBroadcastTower} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            INDUSTRIAL_EQUIPMENT: {code: 'INDUSTRIAL_EQUIPMENT', name: 'Industrial Equipment', icon: <Icon source="fa" icon={faIndustryAlt} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            ENERGY_EQUIPMENT: {code: 'ENERGY_EQUIPMENT', name: 'Energy Equipment', icon: <Icon source="fa" icon={faBolt} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            CRAFTS: {code: 'CRAFTS', name: 'Crafts', icon: <Icon source="fa" icon={faHammer} />,
                cooled: [ELoadCool.STABLE, ELoadCool.NONE],
                measures: [ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT, ELoadMeasure.CONTAINER]}
    }},
    LIVE_ANIMALS: {
        code: 'LIVE_ANIMALS',
        name: 'Live Animals',
        subTypes: {
            BARN_LIVE_ANIMALS: {code: 'BARN_LIVE_ANIMALS', name: 'Barn Animals', icon: <Icon source="fa" icon={faPig} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.NUMBER, ELoadMeasure.WEIGHT]},
            EXOTICS_ANIMALS: {code: 'EXOTIC_ANIMALS', name: 'Exotic Animals', icon: <Icon source="fa" icon={faElephant} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.NUMBER, ELoadMeasure.WEIGHT]},
            COMPETITION_ANIMALS: {code: 'COMPETITION_ANIMALS', name: 'Competition Animals', icon: <Icon source="fa" icon={faHorse} />, 
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],  
                measures: [ELoadMeasure.NUMBER, ELoadMeasure.WEIGHT]},
            OTHER_ANIMALS: {code: 'OTHER_ANIMALS', name: 'Other Animals', icon: <Icon source="fa" icon={faDog} />,
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],
                measures: [ELoadMeasure.NUMBER]}
    }},
    HAZARD: {
        code: 'HAZARD',
        name: 'Hazard',
        subTypes: {
            BIOHAZARD: {code: 'BIOHAZARD', name: 'Biohazard', icon: <Icon source="fa" icon={faBiohazard} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            HAZARD_MATERIAL: {code: 'HAZARD_MATERIAL', name: 'Hazard Materials', icon: <Icon source="fa" icon={faAtom} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            RADIATION: {code: 'RADIATION', name: 'Radiation', icon: <Icon source="fa" icon={faRadiation} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            TOXIC: {code: 'TOXIC', name: 'Toxic', icon: <Icon source="fa" icon={faSkullCrossbones} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            UNSTABLE: {code: 'UNSTABLE', name: 'Unstable Materials', icon: <Icon source="fa" icon={faVial} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            GAS: {code: 'GAS', name: 'Gas', icon: <Icon source="fa" icon={faGasPump} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            FLAMMABLE: {code: 'FLAMMABLE', name: 'Flammable', icon: <Icon source="fa" icon={faBurn} />, 
                cooled: [ELoadCool.FROZEN, ELoadCool.HEATED, ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.EXTRA_DIMENSIONS, ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
    }},
    TRASH: {
        code: 'TRASH',
        name: 'Trash',
        subTypes: {
            TRASH: {code: 'TRASH', name: 'Trash', icon: <Icon source="fa" icon={faTrash} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
            RECYCLE: {code: 'RECYCLE', name: 'Recycle', icon: <Icon source="fa" icon={faRecycle} />, 
                cooled: [ELoadCool.NONE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.VOLUME, ELoadMeasure.WEIGHT]},
    }},
    MEDICAL: {
        code: 'MEDICAL',
        name: 'Medical',
        subTypes: {
            PHARMACEUTICALS: {code: 'PHARMACEUTICALS', name: 'Pharmaceuticals', icon: <Icon source="fa" icon={faPills} />, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            ORGANS: {code: 'ORGANS', name: 'Organs', icon: <Icon source="fa" icon={faLungs} />, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.NUMBER]},
            MEDICAL_FURNITURE: {code: 'MEDICAL_FURNITURE', name: 'Medical Furniture', icon: <Icon source="fa" icon={faSyringe} />, 
                cooled: [ELoadCool.NONE, ELoadCool.REFRIGERATED, ELoadCool.STABLE],  
                measures: [ELoadMeasure.CONTAINER, ELoadMeasure.NUMBER, ELoadMeasure.PALLET, ELoadMeasure.WEIGHT]},
            VISION: {code: 'VISIION', name: 'Vision', icon: <Icon source="fa" icon={faGlasses} />,
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],
                measures: [ELoadMeasure.PALLET, ELoadCool.CONTAINER]},
            TOOTH: {code: 'TOOTH', name: 'Tooth', icon: <Icon source="fa" icon={faTooth} />,
                cooled: [ELoadCool.NONE, ELoadCool.STABLE],
                ELoadMeasure: [ELoadMeasure.CONTAINER, ELoadMeasure.PALLET]}
    }},
});

export default ELoadType;
